config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users 
  resources :sessions
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
    validates :session_token, uniqueness: true
    validates :email, uniqueness: true
    after_initialize :ensure_session_token

   def self.find_by_credentials(email, password)
        user = User.find(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
   end

   def is_password?(password)
        password_object = BCrypt::Password.new(password)
        password_object.is_password?(password)
   end

   def password
        @password
   end

   def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
   end

   def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
   end

   def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in? 

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user 
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
           redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(band_params)
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end


    def band_params
        params.require(:band).permit(:name)
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        if @user.nil?
            flash.now[:errors] = @user.errors.full_messages 
            render :new
        else
            login!(@user)
            redirect_to user_url(@user)
        end
    end

    def destroy
        logout!
        flash[:success] = ['Successfully logged out']
        redirect_to new_session_url
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all 
        render :index
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save   
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
        render :edit
    end

    def update
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            redirect_to user_url(@user)
        else
            render json: @user.errors.full_messages, status: :unprocessable_entity
        end     
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_url
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
    <% @bands.each do |band| %>
        <li><a href="<%= band_url(band) %>"><p> band.name </p></li>
    <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>

app/views/bands/new.html.erb
<h1 class='Page Header'> New Band!</h1>

<%= render "form", band: @band  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class='main-content'>
      <h1 class='main-logo'>Music App</h1>

       <% if logged_in? %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>This is the users</h1>
<% @users.each do |user|  %>
    <%= user %>
<% end  %>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
    <%= auth_token %>

    <label for="email">Email: </label>
    <input type="text" id="email" name="user[email]">
    <label for="username">Username: </label>
    <input type="text" id="username" name="user[username]">
    <label for="password">Password: </label> 
    <input type="password" id="password" name="user[password]">
    <label for="age">Age: </label>
    <input type="number" id="age" name="user[age]">
    <button>Create User</button>

</form>